/**
 * GnuBoard 5 hosting-charset fix: many Korean shared-hosting Apache/Nginx configs default
 * to EUC-KR/CP949, so a plain static `/llms.txt` or `/llms-full.txt` request comes back
 * mangled for browsers and AI crawlers (ChatGPT/Perplexity/Claude). This engine builds an
 * idempotent `llms.php` UTF-8 forcing router (self-contained, no dependency on redue.schema.php)
 * plus the `.htaccess` rewrite block that transparently sends `llms.txt` / `llms-full.txt`
 * requests through it. Re-running the deploy never re-writes unchanged files/marker blocks.
 */

export const LLMS_PHP_ROUTER_RELATIVE_PATH = 'llms.php';

/** Bump when the router body changes — deploy re-uploads only when this differs remotely. */
export const LLMS_UTF8_ROUTER_VERSION = '1.0.0';

const ROUTER_VERSION_MARKER = `REDUE_LLMS_UTF8_ROUTER_v${LLMS_UTF8_ROUTER_VERSION}`;

const HTACCESS_BLOCK_START = '# BEGIN REDUE LLMS UTF-8 Router';
const HTACCESS_BLOCK_END = '# END REDUE LLMS UTF-8 Router';

/**
 * Standalone `llms.php` router source. UTF-8 charset + no-cache headers are forced
 * unconditionally, the target file is chosen from REQUEST_URI (llms-full vs llms),
 * and — if the file itself was ever saved in EUC-KR/CP949 — it is re-encoded to
 * UTF-8 on the fly via `mb_convert_encoding` before being echoed.
 */
export function buildLlmsUtf8RouterPhp(): string {
	return `<?php
/**
 * ${ROUTER_VERSION_MARKER}
 * Auto-generated by REDUE AI Studio — do not edit by hand, it is re-deployed idempotently.
 * Purpose: force UTF-8 delivery of /llms.txt and /llms-full.txt regardless of the
 * hosting environment's default Apache/Nginx/PHP charset (EUC-KR/CP949 on many
 * Korean shared-hosting presets breaks these files for browsers and AI crawlers).
 */

if ( ! headers_sent() ) {
	header( 'Content-Type: text/plain; charset=utf-8' );
	header( 'Cache-Control: no-cache, must-revalidate' );
	header( 'X-Content-Type-Options: nosniff' );
}

$redue_llms_uri = isset( $_SERVER['REQUEST_URI'] ) ? (string) $_SERVER['REQUEST_URI'] : '';
$redue_llms_target = ( strpos( $redue_llms_uri, 'llms-full' ) !== false ) ? 'llms-full.txt' : 'llms.txt';
$redue_llms_file = __DIR__ . '/' . $redue_llms_target;

if ( is_file( $redue_llms_file ) && is_readable( $redue_llms_file ) ) {
	$redue_llms_content = file_get_contents( $redue_llms_file );
	if ( ! is_string( $redue_llms_content ) ) {
		$redue_llms_content = '';
	}
	if ( $redue_llms_content !== '' && function_exists( 'mb_detect_encoding' ) && function_exists( 'mb_convert_encoding' ) ) {
		$redue_llms_encoding = mb_detect_encoding( $redue_llms_content, array( 'UTF-8', 'EUC-KR', 'CP949', 'ASCII' ), true );
		if ( $redue_llms_encoding && $redue_llms_encoding !== 'UTF-8' ) {
			$redue_llms_content = mb_convert_encoding( $redue_llms_content, 'UTF-8', $redue_llms_encoding );
		}
	}
	echo $redue_llms_content;
} else {
	http_response_code( 404 );
	echo "LLMS file not found.";
}
exit;
`;
}

/**
 * True when the already-deployed remote `llms.php` matches the current version marker
 * (so `remote-patch-engine` can skip the re-upload + backup churn entirely).
 */
export function isLlmsUtf8RouterCurrent(existingContent: string): boolean {
	return typeof existingContent === 'string' && existingContent.includes(ROUTER_VERSION_MARKER);
}

/**
 * `.htaccess` block that internally rewrites `llms.txt` / `llms-full.txt` requests to
 * `llms.php` (no `[R]` redirect — the browser/crawler URL never changes) so static-file
 * serving never bypasses the UTF-8 forcing router, plus an `AddType` fallback for hosts
 * that still hit the static file directly (e.g. via a CDN edge cache).
 */
export function buildLlmsHtaccessRewriteBlock(): string {
	return `${HTACCESS_BLOCK_START} (${ROUTER_VERSION_MARKER})
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^llms\\.txt$ llms.php [L]
RewriteRule ^llms-full\\.txt$ llms.php [L]
</IfModule>
<IfModule mod_mime.c>
AddType 'text/plain; charset=UTF-8' .txt
</IfModule>
${HTACCESS_BLOCK_END}`;
}

function findHtaccessBlock(content: string): { start: number; end: number } | null {
	const startIdx = content.indexOf(HTACCESS_BLOCK_START);
	if (startIdx === -1) return null;
	const endMarkerIdx = content.indexOf(HTACCESS_BLOCK_END, startIdx);
	if (endMarkerIdx === -1) return null;
	const end = endMarkerIdx + HTACCESS_BLOCK_END.length;
	return { start: startIdx, end };
}

/**
 * Idempotently insert/refresh the REDUE LLMS UTF-8 Router block inside an existing
 * `.htaccess`. The block is placed at the very top (ahead of any CMS/WordPress catch-all
 * rewrite block) so its `[L]` rule always wins for llms.txt / llms-full.txt requests —
 * mirrors this repo's own `# BEGIN REDUE Performance` convention of staying outside
 * `# BEGIN WordPress`. No-ops (changed: false) when the current version is already present.
 */
export function applyLlmsRouterHtaccessPatch(existingHtaccess: string): {
	content: string;
	changed: boolean;
} {
	const source = typeof existingHtaccess === 'string' ? existingHtaccess : '';
	const block = buildLlmsHtaccessRewriteBlock();
	const existingBlock = findHtaccessBlock(source);

	if (existingBlock) {
		const current = source.slice(existingBlock.start, existingBlock.end);
		if (current === block) {
			return { content: source, changed: false };
		}
		const content = `${source.slice(0, existingBlock.start)}${block}${source.slice(existingBlock.end)}`;
		return { content, changed: true };
	}

	if (!source.trim()) {
		return { content: `${block}\n`, changed: true };
	}

	return { content: `${block}\n\n${source.replace(/^\s+/, '')}`, changed: true };
}
