/**
 * CMS-aware robots.txt builder — shared rule tables for Studio deploy
 * and the standalone PHP module (`templates/redue.robots.php`).
 */

import { normalizeCmsAdapterId, type CmsAdapterId } from '@/lib/solve/adapters';

export type RobotsCmsId = 'gnuboard' | 'wordpress' | 'rhymix' | 'standalone';

export const AI_ROBOTS_CRAWLERS = [
	'GPTBot',
	'ChatGPT-User',
	'PerplexityBot',
	'ClaudeBot',
	'anthropic-ai',
	'Google-Extended',
	'Applebot-Extended',
	'CCBot',
	'Meta-ExternalAgent',
	'Cohere-ai',
] as const;

export type RobotsPathRules = {
	allow: readonly string[];
	disallow: readonly string[];
};

export const ROBOTS_CMS_RULES: Record<RobotsCmsId, RobotsPathRules> = {
	gnuboard: {
		allow: ['/data/file/', '/theme/', '/skin/', '/js/', '/css/'],
		disallow: [
			'/adm/',
			'/admin/',
			'/data/session/',
			'/data/cache/',
			'/data/tmp/',
			'/bbs/write*',
			'/bbs/delete*',
			'/bbs/login*',
			'/bbs/register*',
			'/bbs/password*',
			'/bbs/logout*',
		],
	},
	wordpress: {
		allow: [
			'/wp-admin/admin-ajax.php',
			'/wp-content/uploads/',
			'/wp-content/themes/',
			'/wp-content/plugins/',
		],
		disallow: ['/wp-admin/', '/wp-includes/', '/wp-login.php', '/wp-signup.php', '/xmlrpc.php'],
	},
	rhymix: {
		allow: ['/files/', '/modules/*/tpl/', '/addons/'],
		disallow: [
			'/admin/',
			'/files/config/',
			'/files/cache/',
			'/*act=dispMember*',
			'/*act=dispEditor*',
		],
	},
	standalone: {
		allow: [],
		disallow: ['/admin/', '/adm/', '/session/', '/cache/', '/tmp/'],
	},
};

export const ROBOTS_CMS_LABEL: Record<RobotsCmsId, string> = {
	gnuboard: 'GnuBoard 5 / YoungCart 5',
	wordpress: 'WordPress',
	rhymix: 'Rhymix / XE',
	standalone: 'Standalone / other CMS',
};

export function normalizeRobotsCmsId(cmsType?: string | null): RobotsCmsId {
	const id: CmsAdapterId = normalizeCmsAdapterId(cmsType);
	if (id === 'gnuboard' || id === 'wordpress' || id === 'rhymix') return id;
	return 'standalone';
}

export type DetectRobotsCmsSignals = {
	constants?: readonly string[] | null;
	rootFiles?: readonly string[] | null;
	rootDirs?: readonly string[] | null;
	cmsType?: string | null;
};

function hasName(set: Set<string>, name: string): boolean {
	return set.has(name.toLowerCase());
}

/**
 * Mirror of `redue_detect_robots_cms()` — constants, then folder signatures, then cmsType hint.
 */
export function detectRobotsCmsId(input: DetectRobotsCmsSignals = {}): RobotsCmsId {
	const constants = new Set((input.constants || []).map((name) => String(name || '').trim()));
	if (constants.has('_GNUBOARD_')) return 'gnuboard';
	if (constants.has('ABSPATH')) return 'wordpress';
	if (constants.has('RX_VERSION') || constants.has('__XE__')) return 'rhymix';

	const files = new Set((input.rootFiles || []).map((name) => String(name || '').trim().toLowerCase()));
	const dirs = new Set((input.rootDirs || []).map((name) => String(name || '').trim().toLowerCase()));
	if (hasName(dirs, 'bbs') && hasName(files, 'config.php')) return 'gnuboard';
	if (hasName(files, 'wp-config.php')) return 'wordpress';
	if (hasName(files, 'config.inc.php') && hasName(dirs, 'modules')) return 'rhymix';

	if (input.cmsType) return normalizeRobotsCmsId(input.cmsType);
	return 'standalone';
}

export function resolveRobotsOrigin(targetUrl?: string): string {
	const raw = String(targetUrl || '').trim();
	if (!raw) return '';
	try {
		const url = new URL(raw.includes('://') ? raw : `https://${raw}`);
		return url.origin;
	} catch {
		return '';
	}
}

export type BuildRobotsTxtInput = {
	targetUrl?: string;
	origin?: string;
	cmsType?: string | null;
	cms?: RobotsCmsId;
	constants?: readonly string[] | null;
	rootFiles?: readonly string[] | null;
	rootDirs?: readonly string[] | null;
};

export function buildAiFriendlyRobotsTxt(
	targetUrlOrInput?: string | BuildRobotsTxtInput,
	cmsType?: string | null,
): string {
	const input: BuildRobotsTxtInput =
		typeof targetUrlOrInput === 'string' || targetUrlOrInput == null
			? { targetUrl: targetUrlOrInput || undefined, cmsType }
			: targetUrlOrInput;

	const cms =
		input.cms ||
		detectRobotsCmsId({
			constants: input.constants,
			rootFiles: input.rootFiles,
			rootDirs: input.rootDirs,
			cmsType: input.cmsType ?? cmsType,
		});
	const origin = String(input.origin || resolveRobotsOrigin(input.targetUrl) || '').replace(/\/+$/, '');
	const rules = ROBOTS_CMS_RULES[cms];
	const lines = [
		'# REDUE AI SEO & GEO Studio — CMS-aware robots.txt',
		`# Generated by redue_generate_robots_txt() · detected=${cms} (${ROBOTS_CMS_LABEL[cms]})`,
		'',
		'User-agent: *',
		'Allow: /',
		...rules.allow.map((path) => `Allow: ${path}`),
		...rules.disallow.map((path) => `Disallow: ${path}`),
		'',
	];
	for (const bot of AI_ROBOTS_CRAWLERS) {
		lines.push(`User-agent: ${bot}`, 'Allow: /', '');
	}
	if (origin) {
		lines.push(`Sitemap: ${origin}/sitemap.xml`);
		lines.push('# AI Context Index (llms.txt)');
		lines.push(`# LLMs: ${origin}/llms.txt`);
	} else {
		lines.push('Sitemap: /sitemap.xml');
		lines.push('# AI Context Index (llms.txt)');
		lines.push('# LLMs: /llms.txt');
	}
	lines.push('');
	return lines.join('\n');
}
